# Generated by Django 3.2.5 on 2021-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_gravatar',
            field=models.BooleanField(default=False, null=True, verbose_name='استفاده از گراواتار'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
