# Generated by Django 3.2.5 on 2021-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210803_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه '),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', 'پیش نویس'), ('P', 'منتشر شده'), ('I', 'در حال بررسی'), ('B', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
