# Generated by Django 3.2.5 on 2021-08-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210812_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس آیپی', 'verbose_name_plural': 'آدرس های آیپی'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
