# Generated by Django 3.2.5 on 2021-08-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210812_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='در اسلایدر نمایش داده شود ؟')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
                'ordering': ['-article__publish'],
            },
        ),
    ]
