# Generated by Django 3.2.5 on 2021-08-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20210811_2357'),
        ('comment', '0011_follower'),
    ]

    operations = [
    ]
